#!/usr/bin/env bash

function main {
  local shome="${_sbt_home:-"$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"}"
  source "$shome/script/profile"

  if [[ -n "$(find -L "$shome/vendor/sbt-launch.jar" ! -type l)" ]]; then
    return 1
  fi

  return 0
}

source sub "$BASH_SOURCE" "$@"
